//
//  Colors.swift
//  Shop
//
//  Created by Roland Michelberger on 12.04.17.
//  Copyright © 2017 rolandmichelberger. All rights reserved.
//

import UIKit

struct Colors {
    
    /* Palette generated by Material Palette - materialpalette.com/teal/amber */
    
//    .dark-primary-color    { background: #00796B; }
//    .default-primary-color { background: #009688; }
//    .light-primary-color   { background: #B2DFDB; }
//    .text-primary-color    { color: #FFFFFF; }
//    .accent-color          { background: #FFC107; }
//    .primary-text-color    { color: #212121; }
//    .secondary-text-color  { color: #757575; }
//    .divider-color         { border-color: #BDBDBD; }

    
    static let DarkPrimaryColor = UIColor(rgb: 0x00796B)
    static let PrimaryColor = UIColor(rgb: 0x009688)
    static let LightPrimaryColor = UIColor(rgb: 0xB2DFDB)
    static let AccentColor = UIColor(rgb: 0xffc107)
    static let PrimaryTextColor = UIColor(rgb: 0x212121)
    static let SecondaryTextColor = UIColor(rgb: 0x757575)
    static let DividerColor = UIColor(rgb: 0xBDBDBD)

    static let NavigationBarBarTintColor = DarkPrimaryColor
    static let NavigationBarTintColor = UIColor.white
    static let BackgroundColor = UIColor.white

    static func setupAppeareance() {

        let navigationBarAppearance = UINavigationBar.appearance()
        navigationBarAppearance.barTintColor = NavigationBarBarTintColor
        navigationBarAppearance.tintColor = NavigationBarTintColor
        navigationBarAppearance.titleTextAttributes = [NSForegroundColorAttributeName : PrimaryTextColor]
        
        UITableView.appearance().separatorColor = DividerColor
        
        UILabel.appearance().textColor = PrimaryTextColor
        UITextField.appearance().textColor = PrimaryTextColor
        
        UIStepper.appearance().tintColor = PrimaryColor
    }
    
}

extension UIColor{
    
    convenience init(rgb: UInt) {
        self.init(rgb:rgb, alpha:1.0)
    }
    
    convenience init(rgb: UInt, alpha: CGFloat) {
        self.init(
            red: CGFloat((rgb & 0xFF0000) >> 16) / 255.0,
            green: CGFloat((rgb & 0x00FF00) >> 8) / 255.0,
            blue: CGFloat(rgb & 0x0000FF) / 255.0,
            alpha: alpha
        )
    }
}
